version: '3.9'
services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
    environment:
      PORT: 8080
      MONGODB_URI: mongodb://mongo_db:27017/demo
      NODE_ENV: 'DEV'
    depends_on:
      - mongo_db
volumes:
  mongo_db: {}
